apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080